/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense.system;

import java.awt.Color;

/**
 *
 * @author suran
 */
public class MainController extends javax.swing.JFrame implements Observer {

    private Subject subject;

    /**
     * Creates new form MainController
     */
    public MainController() {
        initComponents();
        setVisible(true);
        comboBox.addItem("Helicopter");
        comboBox.addItem("Tank");
        comboBox.addItem("Submarine");
        comboBox.setEnabled(false);

    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtValueArea = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResiveArea = new javax.swing.JTextPane();
        btnSend = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submarineAmmo = new javax.swing.JLabel();
        helicopterSoldier = new javax.swing.JLabel();
        tankSoldier = new javax.swing.JLabel();
        tankAmmo = new javax.swing.JLabel();
        submarineSoldier = new javax.swing.JLabel();
        helicopterAmmo = new javax.swing.JLabel();
        checkBoxPrivate = new javax.swing.JCheckBox();
        comboBox = new java.awt.Choice();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainController");

        checkBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkBox.setText("Area Clear");
        checkBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxStateChanged(evt);
            }
        });
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        txtArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtArea.setToolTipText("");
        jScrollPane1.setViewportView(txtArea);

        txtValueArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtValueArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtValueArea.setToolTipText("");
        jScrollPane2.setViewportView(txtValueArea);

        txtResiveArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtResiveArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtResiveArea.setToolTipText("");
        jScrollPane3.setViewportView(txtResiveArea);

        btnSend.setBackground(new java.awt.Color(102, 255, 204));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setForeground(new java.awt.Color(0, 0, 0));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        slider.setForeground(new java.awt.Color(0, 0, 0));
        slider.setMajorTickSpacing(20);
        slider.setMinorTickSpacing(10);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setToolTipText("");
        slider.setValue(0);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Helicopter Soldier Count - ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Helicopter Ammo Count - ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tank Soldier Count - ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Submarine Ammo Count - ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tank Ammo Count - ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Submarine Soldier Count - ");

        submarineAmmo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submarineAmmo.setText("0");

        helicopterSoldier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        helicopterSoldier.setText("0");

        tankSoldier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tankSoldier.setText("0");

        tankAmmo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tankAmmo.setText("0");

        submarineSoldier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submarineSoldier.setText("0");

        helicopterAmmo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        helicopterAmmo.setText("0");

        checkBoxPrivate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkBoxPrivate.setText("Private");
        checkBoxPrivate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxPrivateStateChanged(evt);
            }
        });
        checkBoxPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPrivateActionPerformed(evt);
            }
        });

        comboBox.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxItemStateChanged(evt);
            }
        });
        comboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboBoxPropertyChange(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Main Controller");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxPrivate)
                                .addGap(18, 18, 18)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(helicopterSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submarineAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(helicopterAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkBox)
                                .addGap(113, 113, 113))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tankSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tankAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(submarineSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helicopterSoldier))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(helicopterAmmo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(submarineSoldier))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(submarineAmmo))
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tankSoldier)
                                        .addGap(18, 18, 18)
                                        .addComponent(tankAmmo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(checkBox)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSend)
                                    .addComponent(checkBoxPrivate))
                                .addGap(1, 1, 1)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        // TODO add your handling code here:
        if (checkBox.isSelected()) {
            subject.setAreaClear(true);
        } else {
            subject.setAreaClear(false);
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here;
        if (!txtArea.getText().equals("")) {
            if (checkBoxPrivate.isSelected()) {
                subject.setPrivateMessage(comboBox.getSelectedItem(), txtArea.getText());
                checkBoxPrivate.setSelected(false);
                txtArea.setText("");
                comboBox.setEnabled(false);
            } else {
                subject.sendAll(txtArea.getText());
                txtArea.setText("");
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void checkBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_checkBoxStateChanged

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        int value = slider.getValue();
        subject.setButton(value);

    }//GEN-LAST:event_sliderStateChanged

    private void checkBoxPrivateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxPrivateStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPrivateStateChanged

    private void checkBoxPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPrivateActionPerformed
        // TODO add your handling code here:
        comboBox.setEnabled(true);
    }//GEN-LAST:event_checkBoxPrivateActionPerformed

    private void comboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxItemStateChanged

    private void comboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboBoxPropertyChange
        // TODO add your handling code here:


    }//GEN-LAST:event_comboBoxPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainController().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JCheckBox checkBoxPrivate;
    private java.awt.Choice comboBox;
    private javax.swing.JLabel helicopterAmmo;
    private javax.swing.JLabel helicopterSoldier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider slider;
    private javax.swing.JLabel submarineAmmo;
    private javax.swing.JLabel submarineSoldier;
    private javax.swing.JLabel tankAmmo;
    private javax.swing.JLabel tankSoldier;
    private javax.swing.JTextPane txtArea;
    private javax.swing.JTextPane txtResiveArea;
    private javax.swing.JTextPane txtValueArea;
    // End of variables declaration//GEN-END:variables

    public void sendMessageToAll(String value) {
        //
    }

    @Override
    public void sendMessageToMainController(String name, String value) {
        txtResiveArea.setText(name + " : " + value + "\n" + txtResiveArea.getText());
    }

    @Override
    public void sendAreaClear(boolean b) {
        //
    }

    @Override
    public void buttonControl(int value) {
        //
    }

    public void setSpinner(String name, String type, String value) {

        if (name.equals("Helicopter") && type.equals("Soldier")) {
            helicopterSoldier.setText(value);
        }
        if (name.equals("Helicopter") && type.equals("Ammo")) {
            helicopterAmmo.setText(value);
        }
        if (name.equals("Tank") && type.equals("Soldier")) {
            tankSoldier.setText(value);
        }
        if (name.equals("Tank") && type.equals("Ammo")) {
            tankAmmo.setText(value);
        }
        if (name.equals("Submarine") && type.equals("Soldier")) {
            submarineSoldier.setText(value);
        }
        if (name.equals("Submarine") && type.equals("Ammo")) {
            submarineAmmo.setText(value);
        }

    }

    public void setEnergyValue(String name, int value) {
        String stringValue = String.valueOf(value);

        if (value < 30) {
            txtValueArea.setForeground(Color.RED);
            txtValueArea.setText(name + " Energy \n Value : " + stringValue + "\n" + "Denger...");
        } else {
            txtValueArea.setForeground(Color.BLACK);
            txtValueArea.setText(name + " Energy \n Value : " + stringValue);
        }
    }

    public void setOxigienValue(String name, int value) {
        String stringValue = String.valueOf(value);

        if (value < 30) {
            txtValueArea.setForeground(Color.RED);
            txtValueArea.setText(name + " Oxigien Value : " + stringValue + "\n" + "Denger...");
        } else {
            txtValueArea.setForeground(Color.BLACK);
            txtValueArea.setText(name + " Oxigien Value : " + stringValue);
        }
    }

    @Override
    public void getPrivateMessage(String name, String value) {
        //
    }

}
